site_name: My CGMSIM Website
pages:
    - Home: index.md
    - About: about.md
    - Blog: blog.md
theme: flatly
highlightjs: true
site_url: https://lsandini.github.io/cgmsim-site
extra_css:
  - 'css/extra.css'
markdown_extensions:
    - admonition
    - attr_list
    - toc:
        permalink: ⌁
nav:
- Home: 'index.md'
- Build App:
    - Overview: 'build/overview.md'
