site_name: CGMSIM 
theme: 
    name: flatly
    highlightjs: true
site_url: https://lsandini.github.io/cgmsim-site
extra_css:
    - stylesheets/admonitions.css
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - toc:
        permalink: ⌁
    - pymdownx.arithmatex:
      generic: true
nav:

- Home: 'index.md'
- Mathematical Model: 
    - Overview: 'model/overview.md'
    - Mealtime Insulin: 'model/mealtime.md'
    - Long-acting insulin Agonists: 'model/la-agonists.md'
    - Carb absorption from the gut: 'model/food.md'
    - Endogenous Glucose production: 'model/liver.md'
    - Random variation: 'model/random.md'
    - Physical activity: 'model/physical.md'
- Installation: 
    - Overview: 'build/overview.md'
    - Nightscout: 'build/nightscout.md'
    - Linux/Ubuntu: 'build/linux.md'
    - Download: 'build/clone.md'
    - Setup: 'build/setupscript.md'
    - Kickstart: 'build/kickstart.md'
- Using the simulator:
    - Overview: 'operate/overview.md'
    - Declaring insulin doses: 'operate/insulin.md'
    - Declaring meals: 'operate/meals.md'
    - View reports: 'operate/reports.md'
- Contact me: 'contact.md'

