site_name: CGMSIM - reatime CGM trace generator mimicking T1D 
theme: flatly
site_url: https://lsandini.github.io/cgmsim-site
extra_css:
  - 'css/extra.css'
markdown_extensions:
    - admonition
    - attr_list
    - toc:
        permalink: ⌁
nav:
- Home: 'index.md'
- What you need:
    - Overview: 'build/overview.md'
    - Details: 'build/details.md'
- Installation:
    - Ubuntu: 'build/linux machine.md'
    - Nightscout: 'build/Nightscout.md'
- Using the simulator:
    - Food: 'use/food.md'
    - Insulin: 'use/insulin.md'
- Contribute: 'contribute.md'

